[workspace]
members = [
    "packages/db",
    "apps/http-server",
    "packages/kafka",
    "packages/observability",
    "packages/redis",
    "apps/scheduler",
    "apps/auction-engine",
    "apps/grpc",
    "apps/ws-server",
    "packages/grpc-client",
    "apps/notification-worker",
    "apps/gateway-keeper",
    "apps/cdc-worker",
    "apps/search-server",
]
resolver = "2"
