#!/bin/bash
set -euo pipefail

if [ -z "${SECRETS_JSON:-}" ]; then
  echo "Error: SECRETS_JSON environment variable is not set."
  exit 1
fi

# Explicitly load each individual secret from GitHub SECRETS_JSON
export GITOPS_REPO=$(echo "$SECRETS_JSON" | jq -r '.GITOPS_REPO // ""')
export GITOPS_TOKEN=$(echo "$SECRETS_JSON" | jq -r '.GITOPS_TOKEN // ""')
export GHCR_PULL_TOKEN=$(echo "$SECRETS_JSON" | jq -r '.GHCR_PULL_TOKEN // ""')
export KUBECONFIG=$(echo "$SECRETS_JSON" | jq -r '.KUBECONFIG // ""')
export EXPECTED_KUBE_CONTEXT=$(echo "$SECRETS_JSON" | jq -r '.EXPECTED_KUBE_CONTEXT // ""')
export EXPECTED_CLUSTER_NAME=$(echo "$SECRETS_JSON" | jq -r '.EXPECTED_CLUSTER_NAME // ""')
export EXPECTED_CLUSTER_SERVER=$(echo "$SECRETS_JSON" | jq -r '.EXPECTED_CLUSTER_SERVER // ""')
export KUBE_CONTEXTS=$(echo "$SECRETS_JSON" | jq -r '.KUBE_CONTEXTS // ""')
export DATABASE_URL=$(echo "$SECRETS_JSON" | jq -r '.DATABASE_URL // ""')
export REPLICATION_URL=$(echo "$SECRETS_JSON" | jq -r '.REPLICATION_URL // ""')
export CDC_SLOT_NAME=$(echo "$SECRETS_JSON" | jq -r '.CDC_SLOT_NAME // ""')
export CDC_PUBLICATION=$(echo "$SECRETS_JSON" | jq -r '.CDC_PUBLICATION // ""')
export MONGODB_URL=$(echo "$SECRETS_JSON" | jq -r '.MONGODB_URL // ""')
export MONGODB_DB=$(echo "$SECRETS_JSON" | jq -r '.MONGODB_DB // ""')
export REDIS_URL=$(echo "$SECRETS_JSON" | jq -r '.REDIS_URL // ""')
export REDIS_CLUSTER_URL=$(echo "$SECRETS_JSON" | jq -r '.REDIS_CLUSTER_URL // ""')
export REDIS_CLUSTER_URLS=$(echo "$SECRETS_JSON" | jq -r '.REDIS_CLUSTER_URLS // ""')
export REDIS_REMOTE_URL=$(echo "$SECRETS_JSON" | jq -r '.REDIS_REMOTE_URL // ""')
export ELASTICSEARCH_URL=$(echo "$SECRETS_JSON" | jq -r '.ELASTICSEARCH_URL // ""')
export GATEWAY_KEEPER_ADDR=$(echo "$SECRETS_JSON" | jq -r '.GATEWAY_KEEPER_ADDR // ""')
export SEARCH_SERVER_ADDR=$(echo "$SECRETS_JSON" | jq -r '.SEARCH_SERVER_ADDR // ""')
export OPENAI_API_KEY=$(echo "$SECRETS_JSON" | jq -r '.OPENAI_API_KEY // ""')
export GRPC_SERVER_URL=$(echo "$SECRETS_JSON" | jq -r '.GRPC_SERVER_URL // ""')
export GATEWAY_KEEPER_GRPC_URL=$(echo "$SECRETS_JSON" | jq -r '.GATEWAY_KEEPER_GRPC_URL // ""')
export HTTP_SERVER_URL=$(echo "$SECRETS_JSON" | jq -r '.HTTP_SERVER_URL // ""')
export SEARCH_SERVER_GRPC_URL=$(echo "$SECRETS_JSON" | jq -r '.SEARCH_SERVER_GRPC_URL // ""')
export JWT_SECRET=$(echo "$SECRETS_JSON" | jq -r '.JWT_SECRET // ""')
export INTERNAL_SIGNING_KEY=$(echo "$SECRETS_JSON" | jq -r '.INTERNAL_SIGNING_KEY // ""')
export INVITATION_ENCRYPTION_KEY=$(echo "$SECRETS_JSON" | jq -r '.INVITATION_ENCRYPTION_KEY // ""')
export GOOGLE_CLIENT_ID=$(echo "$SECRETS_JSON" | jq -r '.GOOGLE_CLIENT_ID // ""')
export GOOGLE_CLIENT_SECRET=$(echo "$SECRETS_JSON" | jq -r '.GOOGLE_CLIENT_SECRET // ""')
export RAZORPAY_KEY_ID=$(echo "$SECRETS_JSON" | jq -r '.RAZORPAY_KEY_ID // ""')
export RAZORPAY_KEY_SECRET=$(echo "$SECRETS_JSON" | jq -r '.RAZORPAY_KEY_SECRET // ""')
export NEXT_PUBLIC_RAZORPAY_KEY_ID=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_RAZORPAY_KEY_ID // ""')
export SMTP_HOST=$(echo "$SECRETS_JSON" | jq -r '.SMTP_HOST // ""')
export SMTP_PORT=$(echo "$SECRETS_JSON" | jq -r '.SMTP_PORT // ""')
export SMTP_SECURE=$(echo "$SECRETS_JSON" | jq -r '.SMTP_SECURE // ""')
export SMTP_USER=$(echo "$SECRETS_JSON" | jq -r '.SMTP_USER // ""')
export SMTP_PASS=$(echo "$SECRETS_JSON" | jq -r '.SMTP_PASS // ""')
export SMTP_FROM=$(echo "$SECRETS_JSON" | jq -r '.SMTP_FROM // ""')
export GMAIL_USER=$(echo "$SECRETS_JSON" | jq -r '.GMAIL_USER // ""')
export GMAIL_APP_PASSWORD=$(echo "$SECRETS_JSON" | jq -r '.GMAIL_APP_PASSWORD // ""')
export SUPPORT_EMAIL=$(echo "$SECRETS_JSON" | jq -r '.SUPPORT_EMAIL // ""')
export CLOUDINARY_CLOUD_NAME=$(echo "$SECRETS_JSON" | jq -r '.CLOUDINARY_CLOUD_NAME // ""')
export CLOUDINARY_API_KEY=$(echo "$SECRETS_JSON" | jq -r '.CLOUDINARY_API_KEY // ""')
export CLOUDINARY_API_SECRET=$(echo "$SECRETS_JSON" | jq -r '.CLOUDINARY_API_SECRET // ""')
export NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME // ""')
export CLOUDFLARE_R2_ACCOUNT_ID=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_R2_ACCOUNT_ID // ""')
export CLOUDFLARE_R2_ACCESS_KEY_ID=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_R2_ACCESS_KEY_ID // ""')
export CLOUDFLARE_R2_SECRET_ACCESS_KEY=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_R2_SECRET_ACCESS_KEY // ""')
export CLOUDFLARE_R2_ENDPOINT=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_R2_ENDPOINT // ""')
export CLOUDFLARE_R2_BUCKET=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_R2_BUCKET // ""')
export CLOUDFLARE_R2_PUBLIC_URL=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_R2_PUBLIC_URL // ""')
export NEXT_PUBLIC_API_URL=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_API_URL // ""')
export NEXT_PUBLIC_SOCKET_URL=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_SOCKET_URL // ""')
export NEXT_PUBLIC_WS_URL=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_WS_URL // ""')
export NEXT_PUBLIC_WS_BASE_URL=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_WS_BASE_URL // ""')
export NEXT_PUBLIC_SEARCH_API_URL=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_SEARCH_API_URL // ""')
export NEXT_PUBLIC_R2_PUBLIC_URL=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_R2_PUBLIC_URL // ""')
export NEXT_PUBLIC_USE_REMOTE_STOCKFISH=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_USE_REMOTE_STOCKFISH // ""')
export NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$(echo "$SECRETS_JSON" | jq -r '.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY // ""')
export CLIENT_URL=$(echo "$SECRETS_JSON" | jq -r '.CLIENT_URL // ""')
export OTEL_EXPORTER_OTLP_ENDPOINT=$(echo "$SECRETS_JSON" | jq -r '.OTEL_EXPORTER_OTLP_ENDPOINT // ""')
export OTEL_EXPORTER_OTLP_PROTOCOL=$(echo "$SECRETS_JSON" | jq -r '.OTEL_EXPORTER_OTLP_PROTOCOL // ""')
export OTEL_METRIC_EXPORT_INTERVAL=$(echo "$SECRETS_JSON" | jq -r '.OTEL_METRIC_EXPORT_INTERVAL // ""')
export LOG_LEVEL=$(echo "$SECRETS_JSON" | jq -r '.LOG_LEVEL // ""')
export APP_MODE=$(echo "$SECRETS_JSON" | jq -r '.APP_MODE // ""')
export NODE_ENV=$(echo "$SECRETS_JSON" | jq -r '.NODE_ENV // ""')
export AUCTION_ENVIRONMENT=$(echo "$SECRETS_JSON" | jq -r '.AUCTION_ENVIRONMENT // ""')
export LOCK_WORKER_CONCURRENCY=$(echo "$SECRETS_JSON" | jq -r '.LOCK_WORKER_CONCURRENCY // ""')
export KAFKA_BROKERS=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_BROKERS // ""')
export KAFKA_SECURITY_PROTOCOL=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_SECURITY_PROTOCOL // ""')
export KAFKA_REPLICATION_FACTOR=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_REPLICATION_FACTOR // ""')
export KAFKA_BID_PARTITIONS=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_BID_PARTITIONS // ""')
export KAFKA_BACKGROUND_PARTITIONS=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_BACKGROUND_PARTITIONS // ""')
export KAFKA_SSL_CA_BASE64=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_SSL_CA_BASE64 // ""')
export KAFKA_BROKER_CERT_BASE64=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_BROKER_CERT_BASE64 // ""')
export KAFKA_BROKER_KEY_BASE64=$(echo "$SECRETS_JSON" | jq -r '.KAFKA_BROKER_KEY_BASE64 // ""')
export AUCTION_ACTOR_QUEUE_CAPACITY=$(echo "$SECRETS_JSON" | jq -r '.AUCTION_ACTOR_QUEUE_CAPACITY // ""')
export AUCTION_KAFKA_PARTITION_QUEUE_CAPACITY=$(echo "$SECRETS_JSON" | jq -r '.AUCTION_KAFKA_PARTITION_QUEUE_CAPACITY // ""')
export DOWNSTREAM_TIMEOUT_SECS=$(echo "$SECRETS_JSON" | jq -r '.DOWNSTREAM_TIMEOUT_SECS // ""')
export CIRCUIT_FAILURE_THRESHOLD=$(echo "$SECRETS_JSON" | jq -r '.CIRCUIT_FAILURE_THRESHOLD // ""')
export CIRCUIT_OPEN_SECS=$(echo "$SECRETS_JSON" | jq -r '.CIRCUIT_OPEN_SECS // ""')
export GRAFANA_ADMIN_USER=$(echo "$SECRETS_JSON" | jq -r '.GRAFANA_ADMIN_USER // ""')
export GRAFANA_ADMIN_PASSWORD=$(echo "$SECRETS_JSON" | jq -r '.GRAFANA_ADMIN_PASSWORD // ""')
export CLOUDFLARE_API_TOKEN=$(echo "$SECRETS_JSON" | jq -r '.CLOUDFLARE_API_TOKEN // ""')
export TEST_REDIS_URL=$(echo "$SECRETS_JSON" | jq -r '.TEST_REDIS_URL // ""')
export TEST_DATABASE_URL=$(echo "$SECRETS_JSON" | jq -r '.TEST_DATABASE_URL // ""')

echo "Explicit secrets successfully loaded into environment variables."
